// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShop.Infrastructure.Presistence;

#nullable disable

namespace eShop.Infrastructure.Presistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127081222_InitialProduct")]
    partial class InitialProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShop.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Products", "Catalog");
                });

            modelBuilder.Entity("eShop.Domain.Catalog.Product", b =>
                {
                    b.OwnsMany("eShop.Domain.Catalog.ProductOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductOptions", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsMany("eShop.Domain.Catalog.OptionValue", "Values", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<Guid>("ProductOptionId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ProductOptionId");

                                    b2.ToTable("ProductOptionValues", "Catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductOptionId");
                                });

                            b1.Navigation("Values");
                        });

                    b.OwnsMany("eShop.Domain.Catalog.ProductVariant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductVariants", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsMany("eShop.Domain.Catalog.ProductVariantSelection", "Selections", b2 =>
                                {
                                    b2.Property<Guid>("ProductOptionId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("OptionValueId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("ProductVariantId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("ProductOptionId", "OptionValueId");

                                    b2.HasIndex("ProductVariantId");

                                    b2.ToTable("ProductVariantSelections", "Catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductVariantId");
                                });

                            b1.Navigation("Selections");
                        });

                    b.Navigation("Options");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
